---
authors:
  - Ansible Security Team (https://github.com/ansible-security)
dependencies:
  "ansible.netcommon": ">=2.5.1"
  "ansible.utils": ">=2.11.0"
license_file: LICENSE
name: deepsec
namespace: trendmicro
description: Ansible Security Collection for Trend Micro Deep Security
readme: README.md
repository: https://github.com/ansible-collections/trendmicro.deepsec
documentation: https://github.com/ansible-collections/trendmicro.deepsec
homepage: https://github.com/ansible-collections/trendmicro.deepsec
issues: https://github.com/ansible-collections/trendmicro.deepsec/issues
tags:
  - trendmicro
  - deepsec
  - security
  - endpoint
version: "2.1.0"
build_ignore: []
