---
authors:
  - Ansible Security Team (https://github.com/ansible-security)
dependencies:
  "ansible.netcommon": ">=2.0.1"
license_file: LICENSE
name: deepsec
namespace: trendmicro
description: Ansible Security Collection for Trend Micro Deep Security
readme: README.md
repository: https://github.com/ansible-collections/trendmicro.deepsec
issues: https://github.com/ansible-collections/trendmicro.deepsec/issues
tags:
  - trendmicro
  - deepsec
  - security
  - endpoint
# NOTE(pabelanger): We create an empty version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: null
