---
authors:
  - Ansible Security Team (https://github.com/ansible-security)
dependencies:
  "ansible.netcommon": ">=2.5.1"
  "ansible.utils": ">=2.0.0"
license_file: LICENSE
name: deepsec
namespace: trendmicro
description: Ansible Security Collection for Trend Micro Deep Security
readme: README.md
# The URL of the originating SCM repository
repository: https://github.com/ansible-collections/trendmicro.deepsec
# The URL to any online docs
documentation: https://github.com/ansible-collections/trendmicro.deepsec
# The URL to the homepage of the collection/project
homepage: https://github.com/ansible-collections/trendmicro.deepsec
# The URL to the collection issue tracker
issues: https://github.com/ansible-collections/trendmicro.deepsec/issues
tags:
  - trendmicro
  - deepsec
  - security
  - endpoint
# NOTE(pabelanger): We create an empty version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: 2.0.0
build_ignore: []
